name: tech

services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    hostname: localhost
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - 80:80
      - 443:443
      - 22:22
    volumes:
      - ./volume/config:/etc/gitlab
      - ./volume/logs:/var/log/gitlab
      - ./volume/data:/var/opt/gitlab
    shm_size: '256m'
